api/urls.py
from django.urls import path
from .views import VideoView, SubtitleView, statusView

app_name = 'api'

urlpatterns = [
    path('upload/', VideoView.as_view()),
    # not used in production
    path('subtitle/<int:id>/', SubtitleView.as_view()),
    path('status/<str:task_id>/', statusView, name="status"),   # polling task
]

pages/urls.py
from .views import index, subtitleView, progressView
from django.urls import path

app_name = 'pages'

urlpatterns = [
    path('', index, name='index'),
    path('subtitle/<int:id>', subtitleView, name='subtitle'),
    path('progress/<str:task_id>/<int:id>', progressView, name="progress"),
]

video_subtitle/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls', namespace='pages')),
    path('api/', include('api.urls', namespace='api')),
]

api/models.py
from django.db import models


class Video(models.Model):
    file = models.FileField(upload_to='uploads/')


# not used in production
class Subtitle(models.Model):
    content = models.CharField(max_length=1000, default='')
    start_time = models.CharField(max_length=255, default='')
    end_time = models.CharField(max_length=255, default='')

api/views.py
from rest_framework import filters
from rest_framework.generics import CreateAPIView, ListAPIView
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from video_subtitle import celery_app
from .serializers import VideoSerializer, SubtitleSerializer
from .tasks import generateSRT
from .models import Subtitle


def statusView(request, task_id):
    task = celery_app.AsyncResult(task_id)

    return JsonResponse({'status': task.state})


# Not used in production, used in testing
class SubtitleView(ListAPIView):
    serializer_class = SubtitleSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['content']

    def get_queryset(self):
        id = self.kwargs['id']
        return Subtitle.objects.filter(video_id=id)


class VideoView(CreateAPIView):
    serializer_class = VideoSerializer

    def post(self, request, *args, **kwargs):
        video = request.data.get('file')
        handle_upload(video)
        video_name = video.name
        res = super().post(request, *args, **kwargs)
        task = generateSRT.delay(video_name, res.data['id'])

        return redirect(reverse('pages:progress', kwargs={'task_id': task.task_id, 'id': res.data['id']}))


def handle_upload(video):
    with open(f'media/uploads/{video.name}', 'wb+') as f:
        for chunk in video.chunks():
            f.write(chunk)

pages/views.py
import boto3
import json
from django.shortcuts import render
from video_subtitle.config import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY


def index(request):
    return render(request, 'form.html')


def subtitleView(request, *args, **kwargs):

    try:
        dynamo_client = boto3.resource(service_name='dynamodb', region_name='ap-south-1',
                                       aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)

        table = dynamo_client.Table('subs')
        data = table.get_item(Key={'test-key-1': str(kwargs['id'])})
        data = json.loads(data['Item']['srt'])

        context = {'subtitles': data}

    except:
        context = {}

    if request.method == 'POST':
        context.clear()
        context['subtitles'] = []
        query = request.POST['search']

        for subtitle in data:
            if query.lower() in subtitle['content'].lower():
                context['subtitles'].append(subtitle)

    return render(request, 'subtitles.html', context)


def progressView(request, *args, **kwargs):
    context = {
        'task_id': kwargs['task_id'],
        'id': kwargs['id'],
    }
    return render(request, 'progress.html', context)

pages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <title>Subtitle Extractor</title>
    {% block script %}{% endblock %}
  </head>
  <body>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <div id="content">{% block content %}{% endblock %}</div>
  </body>
</html>

pages/templates/form.html
{% extends 'base.html' %} {% block content %}
<h1 class="position-absolute start-50 translate-middle">Subtitle Extractor</h1>
<form action="/api/upload/" method="post" enctype="multipart/form-data">
  <div
    class="input-group position-absolute top-50 start-50 translate-middle w-50"
    id="input-form"
  >
    {% csrf_token %}
    <input
      type="file"
      class="form-control"
      name="file"
      id="inputGroupFile04"
      aria-describedby="inputGroupFileAddon04"
      aria-label="Upload"
      accept="video/*"
    />
    <button
      class="btn btn-outline-secondary"
      type="submit"
      id="inputGroupFileAddon04"
    >
      Upload
    </button>
  </div>
</form>
{% endblock %}

pages/templates/progress.html
{% extends "base.html" %} {% block script %}
<script>
  window.onload = function () {
    function getStatus(url) {
      fetch(url).then(function (response) {
        response
          .json()
          .then(function (data) {
            if (data.status === "SUCCESS") {
              window.location.replace("{% url 'pages:subtitle' id %}");
            } else if (data.status === "FAILURE") {
              document.getElementById("progress").innerHTML =
                "Error while extracting subtitle";
              clearInterval(r);
            }
          })
          .catch(function (error) {
            console.log(error.message);
          });
      });
      var r = setInterval(getStatus, 1000, url);
    }

    var url = "{% url 'api:status' task_id %}";
    getStatus(url);
  };
</script>
{% endblock %} {% block content %}
<div
  class="card position-absolute top-50 start-50 translate-middle"
  style="width: 18rem"
  id="progress"
>
  <div class="card-body">
    <h1 class="card-title">Please Wait</h1>
    <p class="card-text">
      Your video is being uploaded and subtitles are being extracted.
    </p>
  </div>
</div>
{% endblock %}

pages/templates/subtitles.html
{% extends 'base.html' %} {% block content %}
<h1>
  <a href="{% url 'pages:index' %}" style="text-decoration: none; color: black">
    Subtitles Extractor</a
  >
</h1>

{% if subtitles %}
<form method="post">
  <div class="input-group mb-3">
    {% csrf_token %}
    <input
      type="text"
      name="search"
      class="form-control"
      placeholder="Search words"
      aria-label="query"
      aria-describedby="button-addon2"
    />
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
      Search
    </button>
  </div>
</form>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Index</th>
      <th scope="col">Content</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
    </tr>
  </thead>
  <tbody>
    {% for subtitle in subtitles %}
    <tr>
      <th scope="row">{{ subtitle.index }}</th>
      <td>{{ subtitle.content }}</td>
      <td>{{ subtitle.start_time }}</td>
      <td>{{ subtitle.end_time }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<a href="/" style="text-decoration: none; color: black">
  <div
    class="card position-absolute top-50 start-50 translate-middle"
    style="width: 18rem"
    id="progress"
  >
    <div class="card-body">
      <h1 class="card-title">:(</h1>
      <p class="card-text">No subtitle found in this video.</p>
      <p class="card-text">Click this card to return to the home.</p>
    </div>
  </div>
</a>
{% endif %} {% endblock %}